import dev.muazkadan.hellonative.buildlogic.CMakeBuild
import dev.muazkadan.hellonative.buildlogic.currentDesktopPlatform
import dev.muazkadan.hellonative.buildlogic.isMacOsHost
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    id("hellonative.cmake")
}

// Native C++ builds for iOS and desktop. Android builds the same sources via AGP in :native.
val nativeSourceDir = layout.settingsDirectory.dir("native")

fun registerNativeBuild(name: String, configure: CMakeBuild.() -> Unit) =
    tasks.register<CMakeBuild>(name) {
        group = "native"
        sourceDir.set(nativeSourceDir)
        sources.from(fileTree(nativeSourceDir) { include("CMakeLists.txt", "include/**", "src/**", "jni/**") })
        buildDir.set(layout.buildDirectory.dir("cmake/$name/build"))
        installDir.set(layout.buildDirectory.dir("cmake/$name/install"))
        configure()
    }

val buildNativeDesktop = registerNativeBuild("buildNativeDesktop") {
    description = "Builds the shared library for the host OS/arch, laid out for Compose Desktop app resources."
    arguments.addAll("-DNATIVE_GREETING_SHARED=ON", "-DCMAKE_INSTALL_LIBDIR=$currentDesktopPlatform")
    if (isMacOsHost) arguments.add("-DCMAKE_OSX_DEPLOYMENT_TARGET=12.0")
}

// The desktop FFM bindings in src/jvmMain/java are generated by jextract and committed.
// Rerun this after changing native/include/native_greeting.h (needs jextract on PATH).
tasks.register<Exec>("generateFfmBindings") {
    group = "native"
    description = "Regenerates the desktop FFM bindings from the C header with jextract."
    commandLine(
        "jextract",
        "--target-package", "dev.muazkadan.hellonative.ffm",
        "--header-class-name", "NativeGreetingLib",
        "--output", layout.projectDirectory.dir("src/jvmMain/java").asFile.absolutePath,
        nativeSourceDir.file("include/native_greeting.h").asFile.absolutePath,
    )
}

// Exposes the desktop shared library to :desktopApp, which bundles it as app resources.
configurations.consumable("desktopNativeLibsElements") {
    attributes { attribute(Usage.USAGE_ATTRIBUTE, objects.named("desktop-native-libs")) }
    outgoing.artifact(buildNativeDesktop.flatMap { it.installDir })
}

kotlin {
    // JDK 25 for the desktop FFM bindings; Android keeps bytecode compatible with androidApp.
    jvmToolchain(libs.versions.jvmToolchainDesktop.get().toInt())

    android {
        namespace = "dev.muazkadan.hellonative.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions {
            jvmTarget.set(JvmTarget.fromTarget(libs.versions.jvmToolchain.get()))
        }

        androidResources {
            enable = true
        }

        withHostTest {}
    }

    listOf(
        iosArm64() to "iphoneos",
        iosSimulatorArm64() to "iphonesimulator",
    ).forEach { (iosTarget, sdk) ->
        val nativeBuildName = "buildNative${iosTarget.name.replaceFirstChar(Char::uppercase)}"
        val buildNativeIos = registerNativeBuild(nativeBuildName) {
            description = "Builds the static C++ library for ${iosTarget.name}."
            arguments.addAll(
                "-DCMAKE_SYSTEM_NAME=iOS",
                "-DCMAKE_OSX_SYSROOT=$sdk",
                "-DCMAKE_OSX_ARCHITECTURES=arm64",
                // Kotlin/Native's minimum iOS version, so linking never warns about newer objects.
                "-DCMAKE_OSX_DEPLOYMENT_TARGET=15.0",
            )
        }

        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = false
        }

        val nativeGreeting = iosTarget.compilations["main"].cinterops.create("native_greeting") {
            definitionFile.set(project.file("src/nativeInterop/cinterop/native_greeting.def"))
            includeDirs.headerFilterOnly(nativeSourceDir.dir("include"))
            extraOpts("-libraryPath", layout.buildDirectory.dir("cmake/$nativeBuildName/install/lib").get().asFile.absolutePath)
        }
        tasks.named(nativeGreeting.interopProcessingTaskName) {
            dependsOn(buildNativeIos)
        }
    }

    jvm()

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        androidMain.dependencies {
            implementation(projects.native)
        }
    }
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}

tasks.named<Test>("jvmTest") {
    // Load the library exactly like the packaged desktop app does.
    val nativeLibsDir = buildNativeDesktop.flatMap { it.installDir.dir(currentDesktopPlatform) }
    inputs.dir(nativeLibsDir).withPropertyName("nativeLibsDir").withPathSensitivity(PathSensitivity.RELATIVE)
    jvmArgs("--enable-native-access=ALL-UNNAMED")
    jvmArgumentProviders.add(CommandLineArgumentProvider {
        listOf("-Dcompose.application.resources.dir=${nativeLibsDir.get().asFile.absolutePath}")
    })
}

// This library has no Compose UI tests, so its Wasm tests don't need an executable bundle.
// Remove this (and add `binaries.executable()` to wasmJs) if Compose UI tests are added.
tasks.named { it == "checkComposeUiTestConfigurationForWasmJs" }.configureEach {
    enabled = false
}
