// Generated by jextract

package dev.muazkadan.hellonative.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class NativeGreetingLib extends NativeGreetingLib$shared {

    NativeGreetingLib() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class getNativeGreeting {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            NativeGreetingLib.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("getNativeGreeting");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *getNativeGreeting()
     * }
     */
    public static FunctionDescriptor getNativeGreeting$descriptor() {
        return getNativeGreeting.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *getNativeGreeting()
     * }
     */
    public static MethodHandle getNativeGreeting$handle() {
        return getNativeGreeting.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *getNativeGreeting()
     * }
     */
    public static MemorySegment getNativeGreeting$address() {
        return getNativeGreeting.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *getNativeGreeting()
     * }
     */
    public static MemorySegment getNativeGreeting() {
        var mh$ = getNativeGreeting.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("getNativeGreeting");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

